{% set name = "streamlit-aggrid" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f159161c35ed7319f89539f7af4bb3c735fa02f5600b127081c16f970d6e321

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.7,<4.0
  run:
    - pandas >=1.2
    - python >=3.7,<4.0
    - python-decouple >=3.6
    - streamlit >=0.87.0

test:
  imports:
    - st_aggrid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PablocFonseca/streamlit-aggrid
  summary: Streamlit component implementation of ag-grid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxibor
    - timkpaine
