{% set name = "streamlit-aggrid" %}
{% set version = "1.1.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 27bf8b04b09a2f10a4030168c1ac9bea2b262254765e6ba77f72bf42ad004a2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - pandas >=1.4
    - python >={{ python_min }},<4.0
    - python-decouple
    - streamlit >=1.2

test:
  imports:
    - st_aggrid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PablocFonseca/streamlit-aggrid
  summary: Streamlit component implementation of ag-grid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxibor
    - timkpaine
